apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskrequest-controller
  namespace: system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: taskrequest-sa
      containers:
      - name: manager
        image: your-registry/taskrequest-controller:latest
        command:
        - /manager
        args:
        - "--metrics-addr=0"
        - "--leader-elect"
        env:
        - name: REDIS_ADDR
          value: "redis:6379"
        resources:
          requests:
            cpu:    "100m"    # 保底 0.1 核
            memory: "128Mi"   # 保底 128Mi
          limits:
            cpu:    "500m"    # 最高 0.5 核
            memory: "512Mi"   # 最高 512Mi
