# config/rbac/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: taskrequest-controller
  namespace: system
rules:
- apiGroups: ["scheduler.rcme.ai"]
  resources: ["taskrequests", "taskrequests/status"]
  verbs: ["get","list","watch","update"]
- apiGroups: [""]
  resources: ["pods","jobs"]
  verbs: ["create","get","list","watch","delete"]
