apiVersion: apps/v1
kind: Deployment
metadata:
  name: priority-queue-controller
  labels:
    app: priority-queue-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: priority-queue-controller
  template:
    metadata:
      labels:
        app: priority-queue-controller
    spec:
      serviceAccountName: priority-queue-controller
      containers:
      - name: controller
        image: priority-queue-controller:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_ADDR
          value: "redis:6379"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: QUEUE_NAME
          value: "taskqueue"
        - name: QUEUE_TTL
          value: "120"
        - name: POLL_INTERVAL
          value: "1.0"
        - name: PROMOTION_INTERVAL
          value: "60"
        - name: MAX_RETRIES
          value: "3"
        - name: QUEUE_TYPE
          value: "redis"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: priority-queue-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: priority-queue-controller
rules:
- apiGroups: ["scheduler.rcme.ai"]
  resources: ["taskrequests"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["scheduler.rcme.ai"]
  resources: ["taskrequests/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: priority-queue-controller
subjects:
- kind: ServiceAccount
  name: priority-queue-controller
  namespace: default
roleRef:
  kind: ClusterRole
  name: priority-queue-controller
  apiGroup: rbac.authorization.k8s.io
