# config/crd/bases/scheduler.rcme.ai_taskrequests.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: taskrequests.scheduler.rcme.ai
spec:
  group: scheduler.rcme.ai
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                priority:
                  type: integer
                payload:
                  type: object
  scope: Namespaced
  names:
    plural: taskrequests
    singular: taskrequest
    kind: TaskRequest
